### PR TITLE
Archive translations explainer

### PR DESCRIPTION
**Pull request by christianliebel**
This is now picked up in https://github.com/w3c/manifest/pull/1101.

### CODE REVIEW

**Comment by dmurph** [comment]
Instead of a full delete, can we:
- Create an 'archived' folder to move this into, and
- Add text at the top of the doc to say this is obsolete now and point to your pull request?

**Comment by christianliebel** [comment]
@dmurph Sure, should I move all the other explainers no longer referenced in the README (borderless, note-taking, …) to the _archived_ folder as well?

**Comment by dmurph** [comment]
> @dmurph Sure, should I move all the other explainers no longer referenced in the README (borderless, note-taking, …) to the _archived_ folder as well?

We should only move things that are fully obsolete - I think borderless is being used / referenced still. So perhaps just translations for now?

**Comment by christianliebel** [comment]
SGTM. In that case, this PR should be ready now. 😇

**Review by dmurph — APPROVED** [review]
LGTM

**Pull request merged**
