### PR TITLE
Attempted to generalize `ManifestOverride`

### PR DESCRIPTION
**Pull request by aarongustafson**
* Clarified what to do with excess array items
* Clarified what to do with disallowed keys

@mgiuca @loubrett Thoughts?

### CODE REVIEW

**Comment by loubrett** [comment]
Thanks for adding this! Looks good to me.

I wonder how common it will be to localize shortcut icons. I think of these being universal icons.

**Comment by aarongustafson** [comment]
> I wonder how common it will be to localize shortcut icons. I think of these being universal icons.

Agreed, but I think it probably makes sense to keep the door open to that possibility. After all, iconography is often culturally-tied, so it’s not outside the realm of possibility.

**Comment by tomayac** [comment]
> > I wonder how common it will be to localize shortcut icons. I think of these being universal icons.
> 
> Agreed, but I think it probably makes sense to keep the door open to that possibility. After all, iconography is often culturally-tied, so it’s not outside the realm of possibility.

+1, the [Material Design Guide](https://material.io/design/usability/bidirectionality.html#localization) recommends flipping icons for RTL languages. One of the shortcut icons of Google Maps on iOS is "Send my location" with a Send icon (a paper plane flying to the right, which would fly to the left in RTL).

```html
<svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium MuiSvgIcon-root MuiSvgIcon-fontSizeLarge css-1shn170" focusable="false" viewBox="0 0 24 24" aria-hidden="true" data-testid="SendIcon" tabindex="-1" title="Send"><path d="M2.01 21 23 12 2.01 3 2 10l15 2-15 2z"></path></svg>
```

**Review by loubrett — APPROVED** [review]

**Comment by kenchris** [comment]
What is up with this?

**Pull request merged**
