### PR TITLE
Fix typo in code example

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**
The following code is invalid:

```js
const { userChoice } = await event.prompt();
```

It must be replaced by either:

```js
const userChoice = await event.prompt();
```

or by:

```js
const { outcome, platform } = await event.prompt();
```

***
<a href="https://pr-preview.s3.amazonaws.com/FluorescentHallucinogen/manifest-incubations/pull/93.html" title="Last updated on Feb 14, 2024, 5:18 PM UTC (4fd0ecc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/manifest-incubations/93/490f4af...FluorescentHallucinogen:4fd0ecc.html" title="Last updated on Feb 14, 2024, 5:18 PM UTC (4fd0ecc)">Diff</a>

### CODE REVIEW

**Comment by FluorescentHallucinogen** [comment]
@alancutter @mgiuca PTAL. :wink:

**Comment by FluorescentHallucinogen** [comment]
@alancutter @mgiuca PTAL. 😉

**Comment by FluorescentHallucinogen** [comment]
@aarongustafson Could you please merge this pull request? ;)

**Comment by FluorescentHallucinogen** [comment]
Ping.

**Review by marcoscaceres — APPROVED** [review]

**Pull request merged**
